spring:
  application:
    name: pos-system

#  datasource:
#    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:pos_system}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${DB_USERNAME:root}
#    password: ${DB_PASSWORD:Gan@25453}

  datasource:
    url: jdbc:mysql://${DB_HOST:gondola.proxy.rlwy.net}:${DB_PORT:30459}/${DB_NAME:railway}
#    url: jdbc:mysql://${DB_HOST:mysql.railway.internal}:${DB_PORT:3306}/${DB_NAME:railway}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:pUzwZYlrKNFyMdWOulYQtJPPiVhobygg}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: robotrek.trekbiz@gmail.com
    password: trekbiz@robotrek1
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  devtools:
    livereload:
      enabled: true

server:
  port: 5000

razorpay:
  api:
    key: your razor pay key
    secret: your razorpay secret key

stripe:
  api:
    key: your stripe key



app:
  frontend:
    reset-url: http://localhost:5173/auth/reset-password?token=

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
